#! onが'on'なのはyttが変な挙動をするため
name: キャッシュ
'on': push

jobs:
  install-k14s:
    name: k14sをインストール
    runs-on: ubuntu-latest
    steps:
      - name: k14sのinstall.shをダウンロード
        run: curl -O https://k14s.io/install.sh
      - name: pwdとHOMEを見る
        run: pwd && echo ${HOME}
      - name: echoでキャッシュのキーを確認
        run: |
          echo "========"
          echo ${{ runner.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/install.sh')) }}
          echo "========"
      - name: ls -al でhogeがあるか確認にする
        run: ls -al ${{ github.workspace }}
      - name: k14s全部インストール(もしyttが既にあるのならば、やらない)
        id: install-k14s
        run: |
          ( command -v ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} && echo 'インストールしない') \
          || ( \
            sudo bash install.sh \
            && mkdir -p ${{ format('{0}{1}', github.workspace, '/hoge') }} \
            && sudo mv /usr/local/bin/ytt ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} \
          )
      - name: キャッシュ
        uses: actions/cache@v2.0.0
        with:
          path: ${HOME}
          key: ${{ runner.os }}-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/install.sh')) }}
          restore-keys: ${{ runner.os }}-cache-
      - name: yttのバージョン確認
        run: ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} --version
