#! onが'on'なのはyttが変な挙動をするため
name: キャッシュ
'on': push

jobs:
  install-k14s:
    name: k14sをインストール
    runs-on: ubuntu-latest
    steps:
      - name: k14sのinstall.shをダウンロード
        run: curl -O https://k14s.io/install.sh
      - name: k14s全部インストール(yttだけ移動)
        id: install-k14s
        run: |
          sudo bash install.sh
          mkdir -p ${{ format('{0}{1}', github.workspace, '/hoge') }}
          sudo mv /usr/local/bin/ytt ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }}
      - name: lsで様子を確認
        run: ls -al ${{ format('{0}{1}', github.workspace, '/hoge') }}
      - name: pwdとHOMEを見る
        run: pwd && echo ${HOME}
      - name: echoでキャッシュのキーを確認
        run: |
          echo "========"
          echo ${{ runner.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/install.sh')) }}
          echo "========"
      - name: キャッシュ(pathはキャッシュの保存先。。)
        uses: actions/cache@v2.0.0
        with:
          path: ${HOME}
          key: ${{ runner.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/install.sh')) }}
          restore-keys: ${{ runner.os }}-
      - name: yttのバージョン確認
        run: ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} --version
