#! onが'on'なのはyttが変な挙動をするため
name: キャッシュ
'on': push

jobs:
  install-k14s:
    name: k14sをインストール
    runs-on: ubuntu-latest
    steps:
      - name: hogeディレクトリ作成
        run: mkdir -p ${{ format('{0}{1}', github.workspace, '/hoge') }}
      - name: apt-get install tree
        run: sudo apt-update && sudo apt-get install -y tree
      - name: k14sのinstall.shをダウンロード
        run: curl -O https://k14s.io/install.sh
      - name: キャッシュ
        uses: actions/cache@v2.0.0
        with:
          path: ${{ format('{0}{1}', github.workspace, '/hoge') }}
          key: ${{ runner.os }}-sand-${{ hashFiles(format('{0}{1}', github.workspace, '/install.sh')) }}
          restore-keys: ${{ runner.os }}-sand-
      - name: treeしてみる
        run: tree ${{ github.workspace }}
      - name: k14s全部インストール(もしyttが既にあるのならば、やらない)
        id: install-k14s
        run: |
          ( command -v ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} && echo 'インストールしない') \
          || ( \
            sudo bash install.sh \
            && mkdir -p ${{ format('{0}{1}', github.workspace, '/hoge') }} \
            && sudo mv /usr/local/bin/ytt ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} \
          )
      - name: yttのバージョン確認
        run: ${{ format('{0}{1}', github.workspace, '/hoge/ytt') }} --version
