#! onが'on'なのはyttが変な挙動をするため
name: キャッシュ
'on': push

jobs:
  install-k14s:
    name: k14sをインストール
    runs-on: ubuntu-latest
    steps:
      - name: k14sのinstall.shをダウンロード
        run: curl -O https://k14s.io/install.sh
        working-directory: /tmp/
      - name: k14s全部インストール（わざと10秒かける）
        id: install-k14s
        run: sleep 10 && sudo bash install.sh
        working-directory: /tmp
      - name: キャッシュ
        uses: actions/cache@v2.0.0
        with:
          path: /usr/local/bin/
          key: ${{ runner.os }}-${{ hashFiles('/tmp/install.sh') }}
          restore-keys: ${{ runner.os }}-
      - name: yttのバージョン確認
        run: ytt --version
